Teste 12 cursos completos ganha licençapremium
h4ad-facens/h4ad.facens.ac1.engenharia-de-software pull request #1
Opened 2023-03-29 20:40 UTC by EnricoEng

Por gentileza, me ajude a resolver este pois está dando problema

2023-03-29 22:32 UTC, H4ad requested changes

2023-03-29 22:32 UTC, H4ad commented on src/models/student.ts
> +    this.courses[course];
Troca para `this.courses.push(course);`

2023-03-29 22:32 UTC, H4ad commented on src/models/student.ts
> +    return this.courses[index];
Remove o index e retorna a lista.

Quando quiser pegar apenas 1, usa o método find

2023-03-29 22:32 UTC, H4ad commented on test/course.spec.ts
> +      expect(tamanho).toBe(12);
Remove todas essas linhas e faz o seguinte: cria dentro de usuários uma lista de cursos que foram completos.

Cria no serviço de curso um método para marcar que um curso já foi completo pelo usuário, salva na lista que tu criou.

E depois marca 12 vezes que o cara já assistiu, e depois checa a subscription do usuário.

No método de marcar que o usuário completou, tu coloca a verificação que se ele tiver mais que 12, dar o Premium pra ele.

2023-03-31 19:05 UTC, EnricoEng reviewed
Vinicius, alterei o código. Por gentileza, verifique novamente

2023-03-31 19:45 UTC, H4ad requested changes

2023-03-31 19:45 UTC, H4ad commented on test/course.spec.ts
> +      }
troca para apenas `expect(possuiDozeCursos).toEqual(true);`

```suggestion
      expect(possuiDozeCursos).toEqual(true);
```

2023-03-31 19:45 UTC, H4ad commented on test/course.spec.ts
> +      expect(possuiDozeCursos).toEqual(false);
Remove essa linha

```suggestion
```

2023-03-31 19:45 UTC, H4ad commented on test/course.spec.ts
>        expect(true).toEqual('not implemented');
A idea aqui tá legal mas você não implementou a listagem de cursos, você deve criar um CourseService e criar um método para retornar os cursos de acordo com a assinatura do usuário.

2023-03-31 22:54 UTC, merged